name: delete deployment

on:
  workflow_dispatch:

env:
  AZURE_RESOURCEGROUP_NAME: rg-yoshikawa

permissions:
  id-token: write
  contents: read

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - uses: azure/CLI@v1
      with:
        inlineScript: |
          az deployment group delete -g ${{ env.AZURE_RESOURCEGROUP_NAME }} -n main
